services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: iot
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: ["sh", "-c", "/usr/local/bin/wait-for-it.sh db -- /usr/local/bin/init.sh && apache2-foreground"]
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: iot
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_DATABASE: iot
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - app-network

  npm:
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: [ "npm", "run", "watch" ]
    networks:
      - app-network

volumes:
  vendor:

networks:
  app-network:
    driver: bridge